{
 "title": "recy-api Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Http Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Historic P90 response time by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_server_duration_bucket{job=\"recy-api\"}[1m])) by (le,method,path)) * 1000",
     "legendFormat": "{{method}}#{{path}}"
    }
   ]
  },
  {
   "title": "Historic P50 response time by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_bucket{job=\"recy-api\"}[1m])) by (le,method,path)) * 1000",
     "legendFormat": "{{method}}#{{path}}"
    }
   ]
  },
  {
   "title": "HTTP Responses by status code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status,method) (increase(http_server_duration_count{job=\"recy-api\"}[$__rate_interval]))",
     "legendFormat": "{{method}}: {{status}} status"
    }
   ]
  },
  {
   "title": "Top HTTP paths used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (path) (increase(http_server_duration_count{job=\"recy-api\"}[$__rate_interval]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Throughput by status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count{job=\"recy-api\"}[1m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_sum{job=\"recy-api\"}[1m])) * 10\n/\nsum(rate(http_server_duration_count{job=\"recy-api\"}[1m])) ",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Probe Error Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count{status=~\"[45]..\", job=\"recy-api\"}[1m])) by (job) / sum(rate(http_server_duration_count{job=\"recy-api\"}[1m])) by (job)",
     "legendFormat": "error ratio"
    }
   ]
  },
  {
   "title": "Requests Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count{job=\"recy-api\"}[1m])) by (job)",
     "legendFormat": "total requests rate"
    },
    {
     "expr": "sum(rate(http_server_duration_count{status=\"500\", job=\"recy-api\"}[1m])) by (job)",
     "legendFormat": "error responses rate"
    }
   ]
  }
 ]
}